#!/bin/bash
#usage:add-guest {GUEST IP} {Alloc. BW for new guest}  {GUEST ID}
if [ $# -ne 3 ]
	then
		echo "Invalid number of args"
		exit 0
fi

MAX_BW=10
FRIEND_IP=$1
FRIEND_BW=$2 #Minimum bandwidth for new guest
FRIEND_ID=$3 #there must be a flow ID variable for us to keep track of

tc class add dev ifb0 parent 1:1 classid 1:${FRIEND_ID} htb prio 1 rate ${FRIEND_BW}Mbit ceil ${FRIEND_BW}Mbit 
tc qdisc add dev ifb0 parent 1:${FRIEND_ID} handle ${FRIEND_ID}: sfq perturb 10

tc filter add dev ifb0 protocol ip parent 1: handle ::${FRIEND_ID} prio 1 u32 match ip src ${FRIEND_IP}/32 flowid 1:${FRIEND_ID}
tc filter add dev ifb0 protocol ip parent 1: handle ::${FRIEND_ID} prio 1 u32 match ip dst ${FRIEND_IP}/32 flowid 1:${FRIEND_ID}

echo $FRIEND_ID $FRIEND_BW >> friendlist
