#!/bin/bash
#CHANGE GUEST BW
if [ $# -ne 2  ]
	then
		echo "ERROR: Invalid number of args."
		exit 0
fi 

GUEST_ID=$1
NEW_GUEST_BW=$2
MAX_BW=10

tc class change dev ifb0 parent 1:20 classid 1:${GUEST_ID} htb rate ${NEW_GUEST_BW}Mbit ceil ${MAX_BW}Mbit
