#!/bin/bash
if [ $# -ne 1  ]
	then
		echo "ERROR: Invalid number of args."
		exit 0
fi 

NEW_GUEST_BW=$1
MAX_BW=10

tc class change dev ifb0 parent 1:1 classid 1:10 htb rate $((MAX_BW-NEW_GUEST_BW))Mbit ceil ${MAX_BW}Mbit
tc class change dev ifb0 parent 1:1 classid 1:20 htb rate ${NEW_GUEST_BW}Mbit ceil ${MAX_BW}Mbit
