#!/bin/bash
#Prioritize owners' traffic over guests
IF_OWNER=wlan0 #input interface where owners connect to
IF_GUEST=wlan1 #input interface where guests connect to
MAX_BW=10 #Mbit
BW_OWNER=7 #guaranteed bw in Mbit for owners
BW_GUEST=3 #guaranteed bw in Mbit for guests
NET_OWNER=192.168.12.0
NET_GUEST=192.168.13.0

tc qdisc del dev ifb0 root handle 1: htb
tc qdisc add dev ifb0 root handle 1: htb default 99
tc class add dev ifb0 parent 1: classid 1:1 htb rate ${MAX_BW}Mbit burst 15k

tc class add dev ifb0 parent 1:1 classid 1:10 htb prio 1 rate ${BW_OWNER}Mbit ceil 9Mbit #${MAX_BW}Mbit
tc class add dev ifb0 parent 1:1 classid 1:20 htb prio 2 rate ${BW_GUEST}Mbit ceil 1Mbit #${MAX_BW}Mbit

tc qdisc add dev ifb0 parent 1:10 handle 10: sfq perturb 10
tc qdisc add dev ifb0 parent 1:20 handle 20: sfq perturb 10

tc class add dev ifb0 parent 1:20 classid 1:99 htb rate 100kbit ceil ${MAX_BW}Mbit #classid 99 for unclassified guests
tc qdisc add dev ifb0 parent 1:99 handle 99: sfq perturb 10

tc filter add dev ifb0 protocol ip parent 1: prio 5 u32 match ip src ${NET_OWNER}/24 flowid 1:10
tc filter add dev ifb0 protocol ip parent 1: prio 5 u32 match ip dst ${NET_OWNER}/24 flowid 1:10

tc qdisc del root dev $IF_OWNER
tc qdisc add dev $IF_OWNER root handle 1: htb

tc class add dev $IF_OWNER parent 1: classid 1:1 htb rate ${MAX_BW}Mbit burst 15k

tc filter add dev $IF_OWNER protocol ip parent 1: prio 1 u32 match ip src ${NET_OWNER}/24 flowid 1:1 \
action mirred egress redirect dev ifb0
tc filter add dev $IF_OWNER protocol ip parent 1: prio 1 u32 match ip dst ${NET_OWNER}/24 flowid 1:1 \
action mirred egress redirect dev ifb0

tc qdisc del root dev $IF_GUEST 
tc qdisc add dev $IF_GUEST root handle 1: htb

tc class add dev $IF_GUEST parent 1: classid 1:1 htb rate ${MAX_BW}Mbit burst 15k

tc filter add dev $IF_GUEST protocol ip parent 1: prio 1 u32 match ip src ${NET_GUEST}/24 flowid 1:1 \
action mirred egress redirect dev ifb0
tc filter add dev $IF_GUEST protocol ip parent 1: prio 1 u32 match ip dst ${NET_GUEST}/24 flowid 1:1 \
action mirred egress redirect dev ifb0
